# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title mode function
#' @description Task:
#' Write a function mode() to determine the most frequently occurring value in an integer
#' vector (mode). If the mode is ambiguous (e.g. for 1, 2, 2, 2, 3, 3, 1, 3), return any mode
#'
#' @param v IntegerVector 
#' @return integer vector of length 1 with mode or length 0 
#' @export
mode <- function(v) {
    .Call('HW6_mode', PACKAGE = 'HW6', v)
}

#' @title simplifies list of numeric vectors to array if possibles
#' @description Task:
#' Write your own implementation of the simplify2array() function. Your function should
#' expect a list of numeric vectors on input.
#'
#' @param L list of numeric vectors
#' @return vector, array or list
#' @export
simplify2array <- function(L) {
    .Call('HW6_simplify2array', PACKAGE = 'HW6', L)
}

#' @title permutations function
#' @description Task:
#' Write an Rcpp function perms() to generate all the possible permutations of the set {1, 2, . . . , n}
#' (for some given n). The function should return a matrix with n! rows and n columns
#'
#' @param n integer
#' @return matrix with n! rows and n columns with permutations
#' @export
perms <- function(n) {
    .Call('HW6_perms', PACKAGE = 'HW6', n)
}

